### ISSUE TITLE
Notice from Auto Translator

### ISSUE THREAD

**Issue by gravydevsupreme** [FriendlySky/KoikatsuENG#1]
Hello,

Just wanted to say two things:

### 1...
Commend the great effort that it is going to take to translate this game. I am sure I am not the only one that is eagerly anticipating this. 👍 👍 👍 

### 2...
Also, I have been looking through some of the translations provided here, and it seems they contain an 'artifact' that I am almost certain is caused by Auto Translator.

Often - but not always, you provide a key text (untranslated text) that contains newlines/japanese whitespace, other times not. And please correct me if I am wrong - this is because you've used the Auto Translator to extract the text, right?

Anyway, just wanted to inform you that I am working on a fix to this problem so newlines should no longer be needed in keys (and no longer be generated either!).

It will be implemented in such a way, that texts with newlines/japanese whitespace, that you've already provided, can still be used as a key (untranslated text).

I am confident this approach is also compatible with the DynamicTranslationLoader, as the text that is initially loaded by the UI components, is the ones without newlines.

This will be released in version 2.3.2.

# Thank you for the translation, and good luck.

**Comment by FriendlySky** [comment]
First of all, thanks! I'll do my best at providing an adequate translation for the game, but there's just so much translating to do.
Secondly, I do use the Auto Translator to dump the game's messages. It saves me the hassle of writing them by hand so all I have to do is copy the message over to my files. Fixing the newline problem would be really great and help reduce the size of the translation files - I appreciate it, thank you very much!
